name: Python Formatter Check

on:
  push:
    branches:
      - pipelines
  pull_request:

jobs:
  black-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Check Code
        run: black --check .

      # - name: Run Black
      #   run: black .